ports:
  - port: 3000
    onOpen: open-browser
    visibility: private

tasks:
  - name: Terminal 1
    before: echo "hello"
    init: |
      ./install.sh
    command: |
      sudo apt-get install entr
      ls *.csv *.json *.sh | entr -r ./start.sh
   - name: Terminal 2
     init: echo "hi, from terminal 2!"

vscode:
  extensions:
    - ms-python.python
